### PR TITLE
This prevents warnings about SQLite3Adapter.represent_boolean_as_integer

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:red_circle: :frowning:

**Comment by jcoyne** [comment]
Yeah, I'm unsure why this caused problems.

**Comment by mjgiarlo** [comment]
@jcoyne should we keep this PR around or close it subsequent to https://github.com/sul-dlss/argo/pull/1299 having been merged?

**Comment by mjgiarlo** [comment]
@jcoyne :point_up: :question:

**Comment by mjgiarlo** [comment]
@jcoyne you still poking at this?

**Comment by aaron-collier** [comment]
@jcoyne this seems closable, correct?

**Pull request closed without merging**
