### PR TITLE
rename workflow configuration variables

### PR DESCRIPTION
**Pull request by drh-stanford**
This addresses the naming issue in #97.

**NOTE** that merging this PR means that we will need to change the shared_configs branches and our local development configurations.

### CODE REVIEW

**Comment by mejackreed** [comment]
If were going to make this change, could we also put them under a different heading in the settings document rather than `#URLS`?

**Comment by drh-stanford** [comment]
ok, i created a new Workflow section in `settings.yml`

**Comment by mejackreed** [comment]
:+1:

**Comment by mejackreed** [comment]
Looks good... A quick review of our config repo. I'm not sure what exactly needs to change there. Should these setting be different for our various env?

**Comment by drh-stanford** [comment]
No, they can be the same for all envs. So I think the defaults in `config/settings.yml` should suffice.

**Pull request merged**
