### PR TITLE
Download descriptive CSV from the show page

### LINKED ISSUE #3015: Add "Download CSV" of descriptive metadata for single-objects that outputs a spreadsheet
For single objects in Argo, add an option (in the red buttons) to download a spreadsheet containing the descriptive metadata for that object. The goal is to give people an editable file that can then be uploaded directly to the object. The upload CSV will be ticketed separately.

This is intended to replace direct XML editing and to be more user-friendly than editing the Cocina JSON.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔
Fixes #3015

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

**Review by justinlittman — APPROVED** [review]
Approve pending consideration of question.

**Comment by arcadiafalcone** [comment]
The source ID should appear in the second column (after druid) with header "sourceId."

**Comment by arcadiafalcone** [comment]
The header ordinal numbers should start with 1 instead of 0.

**Comment by arcadiafalcone** [comment]
Yes, any changes I mention here should also apply to the bulk download.

**Review by mjgiarlo — APPROVED** [review]

**Comment by arcadiafalcone** [comment]
Dates in structured values (date ranges) are not appearing in the output (ex. cc262xq5907). May be related to first record in spreadsheet having simple date only (testing with download of data in this collection: https://argo-stage.stanford.edu/view/druid:bz491mc6190).

**Comment by arcadiafalcone** [comment]
(Bulk download) Group similar columns together in order - contributor2 columns should immediately follow contributor1 columns (ex. jn362bp1522 in sample set).

**Comment by arcadiafalcone** [comment]
Sure, will do.

**Pull request merged**
