### PR TITLE
make mysql a production gem

### PR DESCRIPTION
**Pull request by drh-stanford**
we're not using mysql except in production

### CODE REVIEW

**Comment by mejackreed** [comment]
:+1:

**Comment by jmartin-sul** [comment]
actually, i use mysql on my laptop.  we once ran into a bug that didn't show up in sqlite, but did in mysql (due to some date formatting monkey patching).  so i've kept running mysql just to suss out incompatibilities earlier.  

also, we deploy to dev without production, so i think this would break dev deployments (all the canonical VM deployments use mysql):
https://github.com/sul-dlss/argo/blob/develop/config/deploy/dev.rb#L5

**Comment by mejackreed** [comment]
:clap: good points @jmartin-sul

**Comment by drh-stanford** [comment]
i think that would argue for the `database.yml` to use mysql for development and test. but i'm closing the PR as we have other priorities now

**Pull request closed without merging**
