### PR TITLE
Update registration grid actions styles

### PR DESCRIPTION
**Pull request by jcoyne**
This removes the multiple select and the lock button per the designs.

## Why was this change made? 🤔

Ref #3514

## How was this change tested? 🤨
locally, test suite, on stage by Andrew
Screen Shot 2022-04-18 at 4 10 47 PM

### CODE REVIEW

**Comment by andrewjbtw** [comment]
I see I should have put this in the "redesign" ticket: we implemented auto-suggest for tags on the old form that we should support after redesign. It's been helpful for people wanting to reuse existing tags.

**Comment by jcoyne** [comment]
@andrewjbtw are you saying that the autosuggest is no longer working?

**Comment by andrewjbtw** [comment]
Oh, I keep forgetting to try different tags on stage vs. prod. Sorry. I'm seeing it now.

**Comment by andrewjbtw** [comment]
Switching from grid view to text view is doing some strange things. When you choose the text view, the buttons remain visible in the background:

Screen Shot 2022-04-19 at 2 40 41 PM

In the text view, the farthest left column should be the "barcode" column. But it looks like the unlabeled column on the grid, which is there to signal if there are errors, is being treated as an enter-able field, which shifts the tab arrangement over one position. I pasted some data that I used in prod registration and the alignment when I switch back to grid view is off by one:
Screen Shot 2022-04-19 at 2 58 27 PM

That input should be filling in "catkey", "source id" and "label".

**Comment by andrewjbtw** [comment]
Sample input data to go along with above: 

```
	6553131	sul:CSt-112-1360		6553131
	6553136	sul:CSt-112-1364		6553136
	6553344	sul:CSt-112-1368		6553344
	6553358	sul:CSt-112-1372		6553358
	6553379	sul:CSt-112-1376		6553379
	6553407	sul:CSt-112-1380		6553407
	6553465	sul:CSt-112-1384		6553465
	6553503	sul:CSt-112-1388		6553503
	6553587	sul:CSt-112-1392		6553587
	6553715	sul:CSt-112-1396		6553715
```

**Comment by andrewjbtw** [comment]
Probably a question for Astrid: since we don't know how long the grid could be, maybe the buttons should go above it. I pasted in 300 druids and that pushed the interface way down the page.

**Comment by jcoyne** [comment]
The current library, when switching to "text" depends on there being nothing at the bottom of the page.  So, even if the buttons weren't showing through, they would be inaccessible.

**Comment by jcoyne** [comment]
@andrewjbtw Thank you for your feedback. Can you retest it now?

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
