### PR TITLE
Check for authorization using Cocina models

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by ndushay — CHANGES_REQUESTED** [review]
I think this might need to be vetted by Andrew or is there already an integration test for this permission?

**Comment by jcoyne** [comment]
@ndushay we never grant the `Dor::AdminPolicyObject` permission in Ability, so the only way this ever works is when you are an admin and get `:manage, :all` permissions, thus there is nothing that Andrew could test and there is no way to write an integration test for it.

**Comment by ndushay** [comment]
wouldn't a test be:  if you have admin permission, you can see the Register APO link, and if you don't have admin permission, you can't see the link?   That seems testable

**Comment by jcoyne** [comment]
@ndushay like this? https://github.com/sul-dlss/argo/blob/main/spec/features/apo_spec.rb#L111

**Review by ndushay — APPROVED** [review]
The spec you reference has a reference to Dor.find, by the way - https://github.com/sul-dlss/argo/blob/main/spec/features/apo_spec.rb#L88

I think what I'm concerned about is ... gee this one line change looks fine in isolation, but ... so do a lot of changes and we have broken a lot of stuff in production by not foreseeing the implications of changes.   

Really, what I was trying to say was:  if you pause and step back ... is there a way to test that this has no deleterious affects?  That cocina truly does have the correct information this change depends on;  that we have tested that the change works both when permissions are supposed to be granted and when they aren't?   That we have test code to check both those conditions if at all possible?

You are better placed to know the answers to those questions than I am, and I trust you.

**Comment by jcoyne** [comment]
@ndushay 

The Dor find in that spec gets removed in a different PR that decouples the APO from from Fedora 3.

I don't see a way to test this beyond what we already have since we give the administrators wildcard access.  I do know that the existing code fails here when we decouple from dor-services. If you have suggestions on what I should do, I'd be pleased to entertain them.

**Pull request merged**
