### PR TITLE
Increase Delayed Job column size to accommodate many more druids when…

### PR DESCRIPTION
**Pull request by tingulfsen**
… creating a new job.

### CODE REVIEW

**Comment by tingulfsen** [comment]
Fixes #652

**Comment by ndushay** [comment]
:+1:  from me.  Again, @jkeck may have some insights as he is more knowledgeable re: databases.

**Comment by jmartin-sul** [comment]
:+1: from me too.

can we test it on stage?

**Comment by LynnMcRae** [comment]
We can test this on stage but need to be told if/when it is on stage please.

**Comment by jkeck** [comment]
:+1:

**Comment by ndushay** [comment]
also: are we waiting for verification that this code fixes the problem before we merge?

**Comment by tingulfsen** [comment]
Yep, it would be ideal to verify in staging before merging, although I don't think merging at this time would do anything bad.

**Comment by LynnMcRae** [comment]
From a large run this afternoon:
screen shot 2016-03-29 at 6 05 34 pm

- From the download file, all but one object's descMetadata was downloaded
- From the Log, there was one error midway with detail diagnostics, then the run seemed to resume just fine (Tommy has the log)
- So the numbers reported are off but the utility definitely want way past the older ~500 item limit and processed them correctly.

**Pull request merged**
