### PR TITLE
Use alternative function to wait for applied params

### PR DESCRIPTION
**Pull request by darrenleeweber**
Attempting to work around intermittent travis failures with a wait function that delays a bit longer each time it waits.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
The wait time in each loop of this function are `[*1..45].map {|n| 2 * Math.log(n)}` -- if the wait loop runs to completion it should fail the spec.

**Comment by darrenleeweber** [comment]
When these specs fail, it doesn't seem to matter how long it waits.  It seems the JS gets jammed.  Maybe relevant:
  - http://stackoverflow.com/questions/16657744/phantomjs-hanging-when-called-from-cli-or-web

**Comment by mejackreed** [comment]
I've had success with this approach https://github.com/sul-dlss/argo/pull/353 which seems to be consistent with other community errors. Data on tries/success recorded here: https://github.com/sul-dlss/argo/pull/352#issue-121720520

**Comment by darrenleeweber** [comment]
#353 is a better solution.

**Pull request closed without merging**
