### PR TITLE
add solr_pid_dumper.rb

### PR DESCRIPTION
**Pull request by jmartin-sul**
add basic methods for dumping pids from solr by object type and writing them to files

### CODE REVIEW

**Comment by jmartin-sul** [comment]
this is a new util class i implemented against the 2.x branch to (as the name implies) dump pids by object type from solr.  i deployed it by hand on old argo 2.x prod.  i ran the version from the first commit in the PR to gather the pid lists used for the january and february full reindexing runs in preperation for the recent argo 3 deployment.

there's actually a good chance this'll never get used again, and so silencing the hound complaints was probably unnecessary (and i didn't bother with the line length ones, and i missed a couple others).  still:  i'd like to merge this for posterity's sake, in case we have to come back and reconsider our old work, since this was a very handy tool and was used twice in a recent deployment process.

**Comment by ndushay** [comment]
@jmartin-sul should this be closed, as travis didn't pass?   Or should it be ported to argo 3?  Or ???

**Comment by jmartin-sul** [comment]
@ndushay:  definitely shouldn't be ported to 3, since argo 3 already has an equivalent `solr_pids` method, and since `write_solr_pids_by_obj_type` could be ported there if/when the need arises (i suspect it will eventually, and i'd probably add the ability to take a target output dir, but i'd rather wait and write more query/indexing code as the need arises).

this branch was pretty much a backport of `solr_pids` from argo 3 to argo 2, plus a method on top of that to dump pids by object type.  this was needed because fedora's `risearch` is unreliable (it returned incomplete results when querying by object type, see issue #380).  but we trusted argo 2's solr index for getting IDs by object type, so we used that to generate the lists used for re-indexing fedora to the argo 3 solr schema (so that collections, APOs, etc would get indexed prior to regular objects).

really, i mostly created this as a branch at the time to make sure i didn't lose work i thought i'd re-use if i lost my laptop or something, since we anticipated having to build the index multiple times.  but i'd also wanted to preserve the logic that was used for the reindexing, in case we care about it when figuring something out in the future.

my guess is that the 2.x build is failing in general, and that this PR isn't failing it specifically.  and as per my prior comment, i don't really anticipate using this code again (or deploying argo 2 again, knock on wood).  this is mostly for posterity's sake, at this point, though i understand/appreciate the hesitancy to merge a failing build.

**Comment by ndushay** [comment]
ok, if you want to merge this, you've got my approval, FWIW.

**Comment by jmartin-sul** [comment]
just so there's a bit more transparency, here are the identically failing builds for 2.x-stable and this branch:
https://travis-ci.org/sul-dlss/argo/builds/105543786
https://travis-ci.org/sul-dlss/argo/builds/113310985

merging, but totally happy to revert if others who haven't chimed in yet object.

**Pull request merged**
