### PR TITLE
enhanced rights setting

### LINKED ISSUE #796: Add location and no-download options to rights-setting tools
Add \<location> and rule=no-download as options in places where we let the user set object level rights:

- On the Item registration form
- "Set rights" blue button
- "Set object rights" bulk update (also fix text of choices to match others)
- default rights on APO register/edit form

The choices should read thusly in all places:
- World
- World (no-download)
- Stanford
- Stanford (no-download)
- Location spec
- Location music
- Dark (Preserve only)
- Citation only

Item Registration adds an (APO default) indicator when choosing rights. It would be good to have this show up in all places as well, but may be considered outside the scope of this ticket).
screen shot 2016-09-20 at 12 20 16 pm

Note that the number and names of locations will be a growing list over time, but we don't yet have a common place to define and populate a list. Making such a place so that the choices expand as the list grows without code-modifications is highly desired but may be outside the scope of this ticket; the urgent need is to capture the two initial locations we support.

Details on syntax for the resulting rightsMetadata produced are at https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream.

All these tools affect only the unqualified (no file reference) \<access type="read"> block in rightsMetadata. The "no-download" choices simply add that rule to the world and stanford declarations respectively:

```
<access type="read"> 
   <machine> 
       <world rule="no-download"/> 
   </machine> 
</access>

<access type="read"> 
   <machine> 
       <group rule="no-download">stanford</group> 
   </machine> 
</access> 
```
while "location" is in place of world or stanford:
```
<access type="read"> 
   <machine> 
       <location>spec
</location> 
   </machine> 
</access>

<access type="read"> 
   <machine> 
       <location>music</location> 
   </machine> 
</access> 
```

### PR DESCRIPTION
**Pull request by jmartin-sul**
allow setting of location based rights and the no-download rule in:
* item registration
* APO creation/edit (default object rights)
* "set rights" blue button (obj detail page)
* "set rights" bulk update

this also centralizes the list of allowable rights types, and switches to a centralized dor-services call for getting an APO's default rights type.

~~this should stay [WIP] till sul-dlss/dor-services#245 is merged and a new dor-services version is cut, at which time the gemfile should be updated to the newest dor-services version.~~

closes #796

### CODE REVIEW

**Comment by ndushay** [comment]
LGTM;  👍  on merge after dor-services gem updates

**Comment by tingulfsen** [comment]
I am 👍  to merge after the gem updates.

**Comment by mejackreed** [comment]
👍

**Comment by jmartin-sul** [comment]
just took the WIP off now that Gemfile is in its final form.  ready for merge.

**Pull request merged**
