### PR TITLE
Use the auto-generated rails schema.rb file. We should not auto chang…

### PR DESCRIPTION
**Pull request by mejackreed**
…e the quotes here from using Rubocop or any other tool except Rails migrations.

### CODE REVIEW

**Comment by atz** [comment]
Probably should go ahead and add a .rubocop.yml exclusion for the related rule(s) then?

**Comment by mejackreed** [comment]
Yo dawg: https://github.com/sul-dlss/argo/blob/develop/.rubocop.yml#L3-L6

**Comment by mejackreed** [comment]
I don't know if auto fix stuff respects that though.. @atz do you know?

**Comment by atz** [comment]
Yeah, should be able to work it out.  It will look like:
```yml
Style/WhateverRuleItIs:
  Exclude:
    - 'db/schema.rb'
```

**Comment by atz** [comment]
Actually, looks like schema.rb was already excluded from AllCops, so no further specification is needed.

**Comment by mejackreed** [comment]
:cool:

**Pull request merged**
