### PR TITLE
Switch last_accessioned_version to use Sdr::Client from dor-services

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mejackreed** [comment]
Can this go straight to master?

**Comment by cbeer** [comment]
I'm not sure I understand what branching + release strategy you're using. Feel free to do whatever makes sense.

**Comment by jmartin-sul** [comment]
the plan is to switch to focused feature branches off of master, and to delete develop eventually.  but the plan was to first wind down develop by merging all the open PRs against it.

**Comment by cbeer** [comment]
:+1:

**Pull request closed without merging**
