### PR TITLE
[WIP] cleans up the robot index. Removing svg images in favor of classes

### PR DESCRIPTION
**Pull request by mejackreed**
This page still needs some work. Robot queries are inefficient and we should probably use active record groupings rather than the thing we are doing in the view. Also removes routes that I can't verify are being used anywhere.

screen shot 2015-12-17 at 11 39 45 am

### CODE REVIEW

**Comment by drh-stanford** [comment]
@LynnMcRae wants to know what's the entry point to this page? Is it linked in anywhere in the UI?

**Comment by mejackreed** [comment]
No idea. I would prefer to rip out all of this if possible. No idea where the entry point is. It feels like a 1/4 complete feature.

**Comment by mejackreed** [comment]
setting this to WIP until we can get some clarification on this from @LynnMcRae . I think most likely we could probably just rip it all out.

**Comment by mejackreed** [comment]
Close in favor of #390 killing it.

**Pull request closed without merging**
