### PR TITLE
Switch from Faraday to Rest Client, and wait longer for request timeo…

### PR DESCRIPTION
**Pull request by tingulfsen**
…uts.

### CODE REVIEW

**Comment by tingulfsen** [comment]
This pull request partially addresses issues #746  and #731 by extending the timeout on POST requests to the MODSulator server. It also switches over from using Faraday to Rest Client, because I was unable to figure out how to set timeouts with POST requests using Faraday (sad, I know...).

This is only a partial fix, because there are performance issues when large files are uploaded (particularly large XML files). The current workaround is to break the files up into smaller pieces (e.g. under 10M.

During a sprint later this year, we plan to change the processing of XML files such that you can upload a zip file of many small XML files (each corresponding to a single MODS record). This will enable a "round trip" with descriptive metadata download, which currently provides just such a zip file as its output.

**Comment by tingulfsen** [comment]
Note that the changes in app/jobs/modsulator_job.rb tie in with the corresponding changes in modsulator-app sul-dlss/modsulator-app#5

That is the API that is called.

**Comment by jkeck** [comment]
@tingulfsen so the more that I think about it, I wonder if we're taking the wrong approach here.  If setting timeouts in Faraday does not work, we should report that sort of thing upstream.

I just setup the following to test Faraday timeouts for multipart POST requests: https://gist.github.com/jkeck/a973a12d2ea8b2bc4f85e067c9fb4724  This seems to work exactly as I would expect, so I wonder if there isn't something else that is the problem.

I am kind-of uncomfortable with reverting the use of Faraday back to rest-client.  It seems like a step in the wrong direction as we have consciously tried to remove rest-client in our production applications.

**Comment by tingulfsen** [comment]
Superseded by #751

**Comment by ndushay** [comment]
can this be closed for the time being to avoid confusion?

**Pull request closed without merging**
