### PR TITLE
use travis_retry on the build so it retries a few times on failure

### PR DESCRIPTION
**Pull request by drh-stanford**
This PR attempts to address #304 by using `travis_retry`

### CODE REVIEW

**Comment by mejackreed** [comment]
This gem might also be worth checking out. Will only retry the failing specs:

https://github.com/NoRedInk/rspec-retry

**Comment by mejackreed** [comment]
I've had success with this approach https://github.com/sul-dlss/argo/pull/353 which seems to be consistent with other community errors. Data on tries/success recorded here: https://github.com/sul-dlss/argo/pull/352#issue-121720520

**Comment by darrenleeweber** [comment]
Although #353 looks like a good solution, these additional options in this PR and the `rspec-retry` sound good too.  Maybe 3 retries is too much?  I'd rather have one retry to avoid overloading travis when the specs are actually failing.

**Comment by drh-stanford** [comment]
That `rspec-retry` looks good as it has fine-granularity down to the specific test that needs retries. Closing this for now.

**Pull request closed without merging**
