### PR TITLE
Make rake:argo:install create log/ and tmp/ directories if they do no…

### PR DESCRIPTION
**Pull request by tingulfsen**
…t already exist.

### CODE REVIEW

**Comment by mejackreed** [comment]
@tingulfsen are you running into issues if these dir's are not created? Rails should just create these automagically for us

**Comment by atz** [comment]
What part of rails?  We aren't running `rails generate`, for example.

**Comment by cbeer** [comment]
It's also conventional to just check in `log` to git (and, not unheard of to do the same to `tmp`), and gitignore the contents.

**Comment by tingulfsen** [comment]
I actually really like the thought of checking in log/ and tmp/ and then ignoring the contents. Is everyone else happy with that? It seems like a very simple and foolproof way to ensure that the directories will always exist.

**Comment by mejackreed** [comment]
:+1:

**Comment by atz** [comment]
Yeah, you can do that but you will need the directory to have a file in it for git to care about it existing.  Convention is to put a .gitignore in the empty dir, or my preference, to put a README.md in each directory declaring its purpose.  "This is the default application temp directory, as configured by XYZ setting".

**Comment by cbeer** [comment]
Rails, by default, uses `.keep` instead of `.gitignore`.

**Comment by jmartin-sul** [comment]
i'm also :+1: on checking in `log/` and `tmp/`.

**Comment by drh-stanford** [comment]
this PR is moot due to #179 , right?

**Comment by tingulfsen** [comment]
Yeah, I was just waiting to see what the reaction to #179 would be before deleting this pull request.

**Comment by drh-stanford** [comment]
PR #179 is merged so this can be closed.

**Pull request closed without merging**
