### PR TITLE
Upgrade to rails 6.0

### LINKED ISSUE #2625: Upgrade Argo to Rails 6 when dor-services gem dependency is removed

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
Fixes #2625

### CODE REVIEW

**Review by mjgiarlo — COMMENTED** [review]
LGTM. Has it been tested by @andrewjbtw yet?

**Comment by aaron-collier** [comment]
@mjgiarlo I don't think so and likely won't be today. I will work on getting this integration tested today, but expect Andrew's testing next week.

**Review by aaron-collier — CHANGES_REQUESTED** [review]
The following integration tests failed against this branch:

These 2 appear to be the same UI issue @andrewjbtw was able to manually identify in that the modals do not close after the `Update` button is clicked.
```
rspec ./spec/features/create_object_no_files_spec.rb:14 # Use Argo to create an object without any files is expected to have text "opening version for integration testing"
rspec ./spec/features/edit_item_tags_spec.rb:12 # Use Argo to edit administrative tags for a single item is expected to have text "legal_fraud : rhizophora"
```

These 2 appear to fail registration with 422 errors.
```
rspec ./spec/features/sdr_deposit_spec.rb:12 # SDR deposit deposits objects
rspec ./spec/features/bulk_update_metadata_spec.rb:12 # Use Argo to upload metadata in a spreadsheet is expected to have text "Welcome to Argo!"
```

**Comment by jcoyne** [comment]
I fixed the first problem with a commit that uses local forms. The second problem is also an issue in main.

**Comment by aaron-collier** [comment]
4/20 Update: All integration tests now pass. 

Once @andrewjbtw approves and the failing tests passes I will approve/merge.

**Review by aaron-collier — APPROVED** [review]
@andrewjbtw has tested an signed off, once this is green it's good to go.

**Pull request merged**
