### PR TITLE
item controller - resource spec should be fixed

### PR DESCRIPTION
**Pull request by darrenleeweber**
Marked a spec as pending, so this should fail to pass unit testing until it is fixed.

### CODE REVIEW

**Comment by jmartin-sul** [comment]
well... my understanding is that "pending" is for tests that are expected to fail.  but the test claims it "isn't actually testing what it says" (which doesn't necessarily mean it's expected to fail, since it indicates that the test, and not the code being tested, needs the fix).

as such, seems like "skip" is more appropriate than "pending".

**Comment by darrenleeweber** [comment]
The use of `pending` is intentional.  This spec is not testing what it should and, yet, it is passing.  Unless it is marked `pending`, it will never get attention to fix it and make sure it is doing what it should be doing.  So, no, it should not be `skip` unless you never want it fixed?

**Comment by mejackreed** [comment]
@darrenleeweber You have a good point. Would you mind updating to add the failing expectation? That way we know what the expected behavior is and when it is fixed our build should break because the pending spec will pass.

**Comment by atz** [comment]
There is no point running this test as is, so it is a `skip` unless you can actually specify a test condition that should pass but doesn't yet.  It will still show in rspec results with the other pending tests.

**Comment by darrenleeweber** [comment]
Respectfully disagree with @atz on skipping it.  Someone who knows something about this should fix it or remove it entirely if it's never going to be fixed or explain why it will not be fixed in a `skip('explanation')`.

**Comment by atz** [comment]
The explanation is that the test was never fully written (likely what is there was copied).  There are many other "Test unimplemented" specs marked skip.  You are trying to use the skip/pending as a **motivational** tool or an expression of intent.  But the point is that the test isn't written, so its execution is worthless.  Pending tests are expected to fail until some anticipated moment they start passing, at which time the pending line is removed, thereby graduating into regular test status *otherwise unchanged*.  Since this wasn't written and needs to be changed it cannot be pending.  

Note: the semantics of this did change between rspec 2 and 3.  Pending tests must fail for the build to pass now.  

I'd be happy to remove/comment what is there leaving only a skip line.

**Comment by atz** [comment]
Pushed a reworked version of the branch.

**Comment by jmartin-sul** [comment]
my thinking in leaving the original comment is well summarized by @atz above.  i agree that skip/pending shouldn't be a way to force issue prioritization, and that the state of this test does not line up with my semantic understanding of what pending means.  as such, :+1: for the recently pushed skip version.  i'm not usually a fan of committing commented out code, but :ok_hand: with it here, because i haven't taken the time to evaluate whether the old code is even a reasonable starting point for the described test.

**Comment by jmartin-sul** [comment]
filed issue #556 to revisit pending/skipped tests in general

**Comment by darrenleeweber** [comment]
So I took a look at this thing and the `ItemController#resource` only pulls out content metadata DS.  It doesn't seem to do anything with it.  So, this issue might be bigger than just a skipped spec.  What the heck is the resource doing anyway?

**Comment by mejackreed** [comment]
Not sure why we didn't catch this sooner, but looks like we decided to remove all of this anyways in https://github.com/sul-dlss/argo/issues/523#issuecomment-184919607

**Pull request merged**
