### PR TITLE
Allow users with management rights to reset workflow

### LINKED ISSUE #1628: Allows users to reset errored workflow steps on items for which they have manage rights
Users who have "manage" rights to items in an APO should have the ability to rerun (or "set to waiting") workflow steps that are caught in an error state. 

With the implementation of the new drop-down menu for workflow step management for administrative users, the ability to reset workflow steps was removed for non-adminstrative users.

Screen Shot 2019-09-17 at 11 06 45 AM

This ticket is to bring back the ability for non-administrator users to do a workflow step reset only, and limited only to objects to which they have manage rights.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1628

### CODE REVIEW

**Comment by ndushay** [comment]
Before and After pictures, please?

**Comment by andrewjbtw** [comment]
When I test this with impersonate on stage, I don't see any difference. The option to reset still doesn't show up for a user in a group that should be able to manage the item:

Screen Shot 2019-09-18 at 1 42 35 PM

The APO for that item gives manage rights to "developer, metadata-staff, service-manager, spec-staff". 

The screenshot shows the view when impersonating someone with the following workgroups:  

workgroup:sdr:argo-access,workgroup:sdr:manager-role,workgroup:sdr:accessioning,workgroup:sdr:metadata-staff,workgroup:sdr:spec-staff/administrator

**Comment by jcoyne** [comment]
@andrewjbtw what item is that?

**Comment by andrewjbtw** [comment]
It's here https://argo-stage.stanford.edu/view/druid:by299bg5456

**Pull request merged**
