### PR TITLE
Fix logical operators for user permission in views

### PR DESCRIPTION
**Pull request by darrenleeweber**
Simple PR to correct a couple of logical operators.

### CODE REVIEW

**Comment by mejackreed** [comment]
Seems good to me. Should we submit this to `master`?

**Comment by darrenleeweber** [comment]
After merge to develop, also merge to master?  Yes, I suppose it belongs there too.  It's another piece out of the APO that is based on develop and I don't know if it's OK on master.

**Comment by jmartin-sul** [comment]
i assumed we'd merge develop back to master en-masse again this week once develop's settled down.  i'd be inclined to let this get merged to master via that process (rather than a specific backport commit for this).

**Comment by darrenleeweber** [comment]
:+1:

**Pull request merged**
