### PR TITLE
remove mods editor vestigial parts

### PR DESCRIPTION
**Pull request by mejackreed**
Most of this added in 578c124bef85be2f65f653abf475fcc6ff41e007

According to @LynnMcRae  this isn't a feature in Argo anymore.

### CODE REVIEW

**Comment by drh-stanford** [comment]
Can you please elaborate on why we're deleting `jquery.min.js` and the like in this PR? Is everything in `xml/**` tied only to the MODS editor feature?

**Comment by mejackreed** [comment]
Yes correct. Non of these files, (as far as I can tell) are being required or executed anywhere in Argo. We require jquery from the gem here: https://github.com/sul-dlss/argo/blob/develop/app/assets/javascripts/application.js#L13

**Comment by drh-stanford** [comment]
this is working fine for me. there's still a POST route for `/mods` that I'm wondering about too...

**Comment by mejackreed** [comment]
Ah hah. Yeah I wasn't sure if that stuff was used.

**Comment by drh-stanford** [comment]
I'm pretty sure it's broken:

```
curl -X POST --data ''  http://localhost:3000/items/asdf/mods
...
The action &#39;update_mods&#39; could not be found for ItemsController
...
```

**Comment by mejackreed** [comment]
Ah.. yeah. Added here: https://github.com/sul-dlss/argo/commit/578c124bef85be2f65f653abf475fcc6ff41e007

**Pull request merged**
