### PR TITLE
Track deployments via HoneyBadger

### PR DESCRIPTION
**Pull request by atz**
Following the instructions of:
  https://docs.honeybadger.io/ruby/getting-started/tracking-deployments.html

### CODE REVIEW

**Comment by jcoyne** [comment]
We already have this here: https://github.com/sul-dlss/argo/blob/45f0bed989f8152a566c6399efcff735288ac356/Capfile#L29

and you can see it's working: https://app.honeybadger.io/projects/49894/deploys

**Comment by atz** [comment]
Derp, misread the instructions.  You are correct.

**Comment by atz** [comment]
Have we really not previously deployed since 2016 though?

**Comment by jmartin-sul** [comment]
we for sure deployed multiple times in 2017

**Comment by jmartin-sul** [comment]
confirmed by cap's revision log:
```
Branch master (at 94b0e632003049cee0e1acff8fc899f336c25189) deployed as release 20170120001316 by cabeer
Branch master (at eb1d8f2f1045289ccf55ac1df9d1901a3a37ead5) deployed as release 20170324004748 by suntzu
Branch v3.13.0 (at 9134d6bd22df4832fde7e9c9e21abc134c61bf32) deployed as release 20170331052013 by suntzu
Branch v3.14.0 (at c32ef27e5d3b9aaf48a8ffc100e5144922ec2cc2) deployed as release 20170525012848 by suntzu
Branch v3.15.1 (at a9ae6b25de417baa06f6feaa9824fb901a6d2889) deployed as release 20170713231633 by suntzu
Branch v3.15.2 (at 710ac3bfac90fdc4dcec28c7b13cc5ca859c29cf) deployed as release 20170728180403 by suntzu
Branch v3.15.3 (at 802f88f361d1cb2a983dad3ea6ee65414cbe08e6) deployed as release 20170814224537 by suntzu
```

**Pull request closed without merging**
