### PR TITLE
update context workflow to display as table

### LINKED ISSUE #4456: Display better view of workflow context variables
The argo workflow view currently shows any available workflow context as a hash at the bottom of the workflow display. Improve the display (tabular?)

Image

### PR DESCRIPTION
**Pull request by dnoneill**
# Why was this change made?
closes #4456 

Screenshot 2024-05-31 at 1 26 53 PM

# How was this change tested?
Viewing on Argo QA.

### CODE REVIEW

**Comment by justinlittman** [comment]
Will workflow settings always be scalar?

**Comment by dnoneill** [comment]
I checked. Peter pointed to this https://github.com/sul-dlss/dor-workflow-client/blob/main/lib/dor/workflow/response/process.rb#L54-L59

**Comment by justinlittman** [comment]
But that doesn't stop a workflow setting from being an array or another hash or similar?

**Comment by peetucket** [comment]
@alundgard and @andrewjbtw FYI if you want to see how nicer looking workflow context variables look in this PR, see the screenshot

**Review by peetucket — APPROVED** [review]

**Pull request merged**
