### PR TITLE
Add a back to registration form link

### LINKED ISSUE #3780: Registration form: add link to go back to form after registering
@astridu 's design now includes a "Back to form" link. This should take the user back to the form with the settings they just used already selected (including tags). It should not reload the form with the defaults they get when loading it for the first time.

image (2)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔

Fixes #3780

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]

**Comment by andrewjbtw** [comment]
I tested this in stage today. All the settings previously selected were being retained when I clicked on the back-to-form link except for the rights. The rights were being set back to the APO defaults each time I went back. If possible, the back link should retain the rights from the previous registration, even if they're not the APO defaults.

**Comment by andrewjbtw** [comment]
After the latest changes, the rights settings are being preserved. But I found one more issue that I'd probably missed in testing earlier: the "Initial workflow" is being reset to registrationWF when you go back to the form. 

One of the big use cases will be goobiWF users who will be using the back button to change only a tag or two between registrations.

**Comment by justinlittman** [comment]
@mjgiarlo This has undergone some changes since you approved. Would you mind taking another look please?

**Review by mjgiarlo — APPROVED** [review]

**Comment by mjgiarlo** [comment]
@justinlittman @jcoyne Approved. Does this need further testing? If not, :shipit:

**Pull request merged**
