### PR TITLE
In which tcramer writes his first two rake tasks

### PR DESCRIPTION
**Pull request by mjgiarlo**
```
Bundle complete! 71 Gemfile dependencies, 204 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from zalgo:
Ḧ̹͇̟̞̼̲̬Ę̥̰͇̝̺̝̪ͤ ̝͚̘̭̣ͭ͐́C͚̮͈͈̠̭̊̾Ȍ̙̭͚̘̯͍́ͫM̸͇͈̻͍͍̝̯Ĕ̥̝̑͒ͥͩ̅̽Ș̢̹͚̺̩̙̜ͤ
Post-install message from tcramer:

    tcramer is in the house!!!
          🤠
　　　　　🐧🐧🐧
　　　　🐧 　🐧　🐧
　　　👇🏽　  🐧🐧　👇🏽
　　　　　🐧　  🐧
　　　　　🐧　　🐧
　　　　　 👢　　👢
    howdy. I'm the sheriff of rake tasks.
  1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
```

## Why was this change made? 🤔

To help @tomcramer advance his long-standing professional development goals.

## How was this change tested? 🤨

I successfully ran the tasks tcramer wrote.

```
$ rake manage
C̮̲̰̒ͤ̔̐̿o͙̐̓̓ͤ̿̈͋u͕ͯ̈͑̑̐̽ͦl̊́͒҉_̧͔͓͖̖͔̘̭d͉̳̿ͣ̌̐ ͖̜̗̱͗̓͘͞y͒̈̿̐̑̈̍ͤő̵̎͗͗͂̿͐ủ̈̎̓ͪͭ̍̐ ͔͉̰̺̾̓ͪ̑ġ̹̪́͋̅̄͐i̛̩̲̎͒̐͌͒v̜̅͗ͪ̉ͨ̈ͅȅ͔͖̱̜̥͇̆ ̊̑̒҉_̬̰̜̫̭å̆ͪͪ̚͏͕͞ ̉̈̓ͩ̒ͭͥ́5̗ͦ̄ͭͧ̌͜ͅ ̷̢͓̘͓̐͋̄m̏͌ͨ̔͗ͩͫ́ȉ͉ͅn̴̰̣̐u͖̻͉̖ͣͩ͐̅t̡̔ͧͨͯ̂ͪ͜e̡̞̗͖̠͐̐̓ ̑͂͂̿͗͋̉̇d̥̓ͮ̅ͪ͋͗ͩe̐ͧ͋̅̿͆̀̔ḿ͉͎̠̥̼͍͍oͣͭͪ̔̾ͭ̚͝ ̶̝͚̖͈̱̆͟o̡̲̮͎̥̥͛̇ñ̗̗̯͔̥ͪͭ ̛̖̘̉͒ͯ̓͗t̨̩̹̗ͭ̍͋h͉̝̰͇̝͇ͥ̒a͈̦͔̠̋ͧ̕͟ţ̄ͤ̊̐̉̏͝?̡̩̺͋̋̒͛̐
```

Peek 2022-03-04 10-02

### CODE REVIEW

**Review by ndushay — CHANGES_REQUESTED** [review]
hahah - not in argo, pls.

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> hahah - not in argo, pls.

This is not very supportive of @tomcramer's goals. 😢

**Comment by mjgiarlo** [comment]
😱

**Comment by jcoyne** [comment]
Sorry, there's too much work happening here right now.  I need to get this out of the way.

**Pull request closed without merging**
