### PR TITLE
Draw datastreams without depending on ds_specs_ssim

### LINKED ISSUE #2100: Display of datastreams should not depend on ds_specs_ssim
Once done, remove this from the dor_indexing_app.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

This makes the dataflow a lot easier to follow as there's no indirection via dor_indexing_app. This also allows for a smaller solr index. Fixes #2100

## How was this change tested?

Tested locally on my laptop

## Which documentation and/or configurations were updated?
n/a

### CODE REVIEW

**Comment by justinlittman** [comment]
Can you provide some screenshots to provide context?

**Comment by jcoyne** [comment]
@justinlittman there are no visual changes.

**Comment by justinlittman** [comment]
Even if it doesn't result in visual changes, it does involve rendering.

**Comment by jcoyne** [comment]
@justinlittman If nothing is changing, what would a picture show you?

**Comment by justinlittman** [comment]
The context for the change. (That is, what part of the app if affected.)

**Comment by jcoyne** [comment]
Picture attached above.

**Pull request merged**
