### PR TITLE
Tests run without dor-services-app

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

We don't need this server up to run tests.

## Was the documentation updated?

n/a

### CODE REVIEW

**Comment by jmartin-sul** [comment]
i guess sqlite and webmock cover those needs, respectively?

**Comment by jmartin-sul** [comment]
registering similar surprise 😮, but build passes, so merging...

**Comment by jcoyne** [comment]
@ndushay the database is only to support dor-services-app and we don't have any tests that need that.

**Comment by ndushay** [comment]
@jcoyne thanks for the explanation.  Perhaps we should have tests that need dor-services-app, eventually.

**Comment by mjgiarlo** [comment]
I have a vague recollection that we *used to* have tests that needed dor-services-app, but I could be mistaken.

**Pull request merged**
