### PR TITLE
Ensure the manage catkey function works for collections

### LINKED ISSUE #2626: manage catkey blue button is not working for collection objects
**Describe the bug**
It is not possible to use the "Manage catkey" blue button to manage the catkey for a collection object. This manifests in two ways:

- when there is no existing catkey, clicking on the "manage catkey" button pops up a modal with an error:
Screen Shot 2021-04-01 at 3 21 17 PM
- when there is an existing catkey, the modal pops up but any number entered isn't saved

**User Impact**
Users cannot add or update catkeys for collections using the non-XML interface.

**To Reproduce**

When there's no catkey:

1. Go to a collection object such as https://argo-stage.stanford.edu/view/druid:bb434yv9832
2. Click on Manage catkey
3. See error

When there is a catkey:

1. Go to a collection object that has a catkey: https://argo-stage.stanford.edu/view/druid:gt885md8362
2. Click on Manage catkey
3. Enter a number
4. See that the catkey isn't changed

**Expected behavior**
Collections objects should support the same Argo catkey functionality as items.

**Additional context**
It is possible to edit the identityMetadata directly and update the catkey on a collection object that way. So the data itself seems to be handled properly in both Fedora and Cocina.

I believe this is a new bug related to the workcycle. There's a related HB error that only started this morning: https://app.honeybadger.io/projects/49894/faults/78661319

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
Previously there was a null pointer exception when the identification metatata was not present. This was seen happening on collections that don't yet have a catkey.

Refactored catkey management out of ItemsController which had too many responsibilities.

Fixes #2626

### CODE REVIEW

**Review by aaron-collier — CHANGES_REQUESTED** [review]
@andrewjbtw tested on stage and this did not resolve the issue.

**Comment by jcoyne** [comment]
@aaron-collier there were 2 different bugs. Now both are fixed.

**Comment by jcoyne** [comment]
@aaron-collier I'd love to get #2693 into main before rebasing this, because this depends on firming up the pattern for change sets.

**Comment by andrewjbtw** [comment]
Testing on stage, I'm running into problems adding catkeys to items or collections.

For collections:

I tried to add a catkey to this collection: https://argo-stage.stanford.edu/view/druid:qg077zg8699 When I click on the "Update" button in the modal, nothing happens and the identityMetadata is not updated.

For items:

To check on regressions, I also tried to update the catkey for this item: https://argo-stage.stanford.edu/view/druid:bb259kq2628

When I click on the "Update" button in the modal, it appears nothing happens. But the change actually does get made in the identityMetadata

**Comment by aaron-collier** [comment]
the form now seems to function properly, however the entered catkey data is not updated.

**Comment by jcoyne** [comment]
@aaron-collier it's working for me on https://argo-stage.stanford.edu/view/druid:bb131xs4563, what are you looking at?

**Comment by aaron-collier** [comment]
@jcoyne https://argo-stage.stanford.edu/view/druid:qg077zg8699

**Comment by jcoyne** [comment]
That's because dor-services-app doesn't yet map catkeys for collections, but argo does send the right cocina representation.  You can see this in the Events section of argo:

```json
    "identification": {
      "catalogLinks": [
        {
          "catalog": "symphony",
          "catalogRecordId": "119"
        }
      ]
    },
```

**Comment by aaron-collier** [comment]
Ah, ok... ticketed and blocked this one for now.

**Comment by aaron-collier** [comment]
This is getting closer, but still an error:

Now, setting the catkey works, but trying to set the catkey a second time results in:

https://app.honeybadger.io/projects/50568/faults/73702249
and
https://app.honeybadger.io/projects/49894/faults/79085651

displaying this error message:

Screen Shot 2021-04-28 at 2 51 32 PM

**Comment by aaron-collier** [comment]
@jcoyne we can't seem to win with this one: https://app.honeybadger.io/projects/49894/faults/79086263

**Comment by aaron-collier** [comment]
Verified adding and updating work now work.

**Review by aaron-collier — APPROVED** [review]

**Pull request merged**
