### PR TITLE
MODS should be validated before being stored

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Bad data was getting into the repository.

## Was the documentation updated?
n/a

### CODE REVIEW

**Comment by jcoyne** [comment]
holding for argo-stage to be working again

**Comment by mjgiarlo** [comment]
@jcoyne shall we un-hold?

**Comment by andrewjbtw** [comment]
How will an invalid MODS be reported to the user? Will this go in the modsulator log?

**Comment by jcoyne** [comment]
@andrewjbtw it would go into the log file.  I can deploy this branch to staging and you can test.

**Comment by andrewjbtw** [comment]
In testing on stage, a few things have come up:

1. Invalid MODS has been caught, but the log didn't list the druid where the metadata wasn't updated. 

See the log for 2020-02-13 10:18am on this APO: https://argo-stage.stanford.edu/apos/druid:xs835jp8197/bulk_jobs In that case, metadata for 31 druids was sent, but the log lists only 30.

2. MODS may not officially require a <title>, so it's still possible to upload without one.

**Comment by jcoyne** [comment]
Okay, the error was definitely in the log:
`argo-stage-a:/workspace/bulk/druid\:xs835jp8197/2020_02_13_18_18_13_256/log.txt`
```
argo.bulk_metadata.bulk_log_errors druid:bd508dx0953 5:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '#REF' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
```

**Comment by mjgiarlo** [comment]
@jcoyne what is the status of this PR?

**Comment by andrewjbtw** [comment]
From my perspective, I asked Jessica Cebra in Metadata to test as someone who knows the metadata uploads quite well, and I think things are good to go. It looks like invalid MODS is being surfaced to the user-accessible log now.

**Comment by andrewjbtw** [comment]
Some further testing this morning. Looks good.

**Pull request merged**
